import { NextResponse } from "next/server";
import connectDB from "@/lib/db";
import { Quote } from "@/lib/models/Quote";
import nodemailer from "nodemailer";
import fs from "fs";
import path from "path";

export async function POST(req) {
  await connectDB();

  try {
    const formData = await req.formData();
    const data = Object.fromEntries(formData);

    // Ensure uploads folder exists
    const uploadDir = path.join(process.cwd(), "public/uploads");
    if (!fs.existsSync(uploadDir)) {
      fs.mkdirSync(uploadDir, { recursive: true });
    }

    let fileUrl = "";
    let attachment = null;
    const file = formData.get("file");

    if (file && file.name) {
      const buffer = Buffer.from(await file.arrayBuffer());
      const filename = `${Date.now()}-${file.name}`;
      const filePath = path.join(uploadDir, filename);

      fs.writeFileSync(filePath, buffer);
      fileUrl = `/uploads/${filename}`;

      attachment = {
        filename: file.name,
        content: buffer,
      };
    }

    // Store in DB
    const quote = await Quote.create({ ...data, fileUrl });

    // SMTP Transport Config
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST,
      port: Number(process.env.SMTP_PORT),
      secure: true,
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });

    // File Type Detection
    const ext = file?.name?.split(".").pop()?.toLowerCase();
    const imageTypes = ["jpg", "jpeg", "png", "gif", "webp"];
    const embroideryTypes = ["dst", "pes", "jef"];

    let filePreviewHTML = "";

    if (file && imageTypes.includes(ext)) {
      filePreviewHTML = `
        <p><strong>Uploaded Design:</strong></p>
        <img src="cid:file-preview" style="max-width:250px;border-radius:6px;border:1px solid #ddd;margin-top:10px;" />
      `;
      attachment.cid = "file-preview";
    } else if (file && embroideryTypes.includes(ext)) {
      filePreviewHTML = `
        <p><strong>Embroidery File Attached:</strong> .${ext}<br>
        <small>Open in embroidery software (Wilcom / PE Design)</small></p>
      `;
    } else if (file) {
      filePreviewHTML = `<p><strong>File Attached:</strong> .${ext}</p>`;
    }

    // Styled Email Template
    const emailHTML = `
      <div style="background:#f7fafc;padding:25px;font-family:Arial,Helvetica,sans-serif;">
        <div style="max-width:650px;margin:auto;background:white;border-radius:12px;overflow:hidden;border:1px solid #e5e7eb;">
          
          <div style="background:#0e2c1c;color:white;padding:18px 25px;">
            <h2 style="margin:0;font-size:20px;">New Quote Request</h2>
            <p style="margin:4px 0 0;font-size:13px;opacity:0.85;">Submitted by ${data.name}</p>
          </div>

          <div style="padding:25px;color:#333;font-size:15px;line-height:1.6;">
            <h3 style="margin-bottom:10px;color:#0e2c1c;">Client Details</h3>
            <p><strong>Name:</strong> ${data.name}</p>
            <p><strong>Email:</strong> ${data.email}</p>
            <p><strong>Phone:</strong> ${data.phone}</p>
            <p><strong>Company:</strong> ${data.company || "N/A"}</p>
            <p><strong>Website:</strong> ${data.website || "N/A"}</p>

            <hr style="border:none;border-top:1px solid #e5e7eb;margin:20px 0;">

            <h3 style="margin-bottom:10px;color:#0e2c1c;">Project Details</h3>
            <p><strong>Deadline:</strong> ${data.deadline}</p>
            <p><strong>Service Type:</strong> ${data.type}</p>
            <p><strong>Message:</strong><br>
            <span style="background:#f9fafb;padding:10px;border-radius:6px;border:1px solid #e5e7eb;display:block;margin-top:5px;">
              ${data.message}
            </span></p>

            ${filePreviewHTML}

            ${fileUrl ? `
              <div style="margin-top:20px;">
                <a href="${fileUrl}" download 
                  style="background:#0e2c1c;color:white;padding:10px 16px;border-radius:6px;text-decoration:none;font-size:14px;">
                  Download Attachment
                </a>
              </div>
            ` : ""}
          </div>

          <div style="background:#f1f5f9;padding:12px;text-align:center;font-size:13px;color:#555;border-top:1px solid #e5e7eb;">
            Email generated by <strong>ZS Digitizing Quote System</strong>
          </div>
        </div>
      </div>
    `;

    // Send Email
    await transporter.sendMail({
      from: `"ZS Digitizing" <${process.env.SMTP_USER}>`,
      to: process.env.ADMIN_EMAIL,
      subject: `New Quote Request - ${data.name}`,
      html: emailHTML,
      attachments: attachment ? [attachment] : [],
    });

    return NextResponse.json({ success: true, quote });
  } catch (err) {
    console.error("❌ QUOTE API ERROR:", err);
    return NextResponse.json({ success: false, error: err.message }, { status: 500 });
  }


  
}

export async function GET() {
  await connectDB();
  const quotes = await Quote.find().sort({ createdAt: -1 }); // newest first
  return NextResponse.json({ quotes });
}
